import { Flex, List, Modal, Text } from '@mantine/core';
import styles from './DisclaimerModal.module.css';

interface DisclaimerModalProps {
  opened: boolean;
  onClose: () => void;
}

export default function DisclaimerModal({
  opened,
  onClose,
}: DisclaimerModalProps) {
  return (
    <Modal
      opened={opened}
      onClose={onClose}
      title="Disclaimer"
      className={styles.modal}
    >
      <Flex direction="column" gap="md" p="lg">
        <Text className={styles.text}>
          The financial advice provided by this app is generated by AI and is
          for informational purposes only. It should not be considered
          professional financial, investment, tax, or legal advice.
        </Text>
        <Text className={styles.text}>
          By using this app, you acknowledge that:
        </Text>
        <List>
          <List.Item>
            The AI-generated responses may not always be accurate, complete, or
            up to date.
          </List.Item>
          <List.Item>
            You should consult with a qualified financial advisor before making
            any financial decisions.
          </List.Item>
          <List.Item>
            The app and its creators are not responsible for any financial
            losses or decisions made based on the provided information.
          </List.Item>
        </List>
      </Flex>
    </Modal>
  );
}
